title: "Gabriel Matías Lorenz"
description: "Postdoctoral Computational Neuroscientist"
author: "Gabriel Matías Lorenz"
email: gama.lorenz@gmail.com
theme: null
markdown: kramdown
include: ["assets/css"]
