title: "Gabriel Matías Lorenz"
markdown: kramdown
description: "Computational Neuroscience, Information Theory, Neural Data Analysis"
remote_theme: hydecorp/hydejack@v9.1.6 #mmistakes/jekyll-theme-basically-basic
url: "https://mati-lorenz.github.io"
baseurl: ""
author:
  name: "Gabriel Matías Lorenz"
  email: gama.lorenz@gmail.com
  github: gamalorenz
  orcid: 0009-0006-3129-906X
  location: Hamburg, Germany
logo: 'assets/icons/brain.svg'
# Navigation links
#nav:
#  - title: "About"
#    url: /about/
#  - title: "CV"
#    url: /cv/
#  - title: "Research"
#    url: /research/
#  - title: "Contact"
#    url: /contact/
